### ISSUE TITLE
Module build failed: Error: spawn bin/rails ENOENT

### ISSUE THREAD

**Issue by jonhue** [usabilityhub/rails-erb-loader#52]
After adding the ERB loader and adding the `.erb` file extension to my `application` pack, I am getting the following error:

```
ERROR in ./app/webpack/packs/application.js.erb
Module build failed: Error: spawn bin/rails ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ multi (webpack)-dev-server/client?http://localhost:3035 ./app/webpack/packs/application.js.erb
```

it is also happening with the sample `hello_erb.js.erb` pack.

**Comment by rhys-vdw** [comment]
Oh sorry @jonhue, I missed this. `ENOENT` means that there is no `bin/rails` executable to use. You'll need to work out which directory your rails/ruby executable exists in and [configure](https://github.com/usabilityhub/rails-erb-loader#options) the loader to use the correct path. I've got a  couple of example there you can use as reference. Let me know if you need more guidance.

**Comment by rhys-vdw** [comment]
I've marked this as "enhancement" because this error could be caught and a more practical instruction (like the comment I gave above) provided instead.

**Comment by rhys-vdw** [comment]
> it is also happening with the sample hello_erb.js.erb pack.

What is that?

**Comment by jonhue** [comment]
The [webpacker](https://github.com/rails/webpacker/blob/master/README.md#erb) gem generates it when installing the ERB loader.

**Comment by jonhue** [comment]
@rhys-vdw 

Modifying `runner` & `dependenciesRoot` does not appear to solve the problem. I tried each of them with up to four `../`. Relative to which file should these paths be? The configuration? The `.js.erb` files?

**Comment by jonhue** [comment]
Here is a sample app that reproduces the problem: https://github.com/jonhue/test_app

**Comment by jonhue** [comment]
`runner: 'ruby bin\\rails runner'` fixed the problem for me.

**Comment by rhys-vdw** [comment]
Ah. Windoze! We should be using `path.join` for the default path.

**Comment by rhys-vdw** [comment]
Are you sure you need the leading `ruby` though? `bin/rails` should be an executable.

**Comment by jonhue** [comment]
@rhys-vdw I don't know why, but I need it.
