### ISSUE TITLE
Some Rails helpers produce Syntax Error

### ISSUE THREAD

**Issue by xbl4cky** [usabilityhub/rails-erb-loader#82]
Hello and thank you for this great project!

I installed the **rails-erb-loader** package via the recommended command `bundle exec rails webpacker:install:erb` at Ruby version 2.5.3 and Rails version 5 and Webpacker version 4.0.7. 

When I included the automatically generated JavaScript pack file `hello_erb.js.erb`, the expected result was shown. Then I tried a different ERB code: a simple `content_tag` with the content passed as a parameter - success. But then I tried to pass the content as a block and a syntax error occurred in the Rails console. Also a few ERB codes fail without even including a block.

How can I fix this behavior?

Code example:
```js

// Include native helpers (for "content_tag")
<% include ActionView::Helpers %>

// This works. # => <div>Example 1</div>
console.log(`<%= content_tag(:div, 'Example 1') %>`);

// This fails. # => See below
console.log(`<%= content_tag(:div) do %>Example 2<% end %>`);

```

The error from the Rails console:
```

/home/anonymous/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/erb.rb:876:in `eval': (erb):7: syntax error, unexpected ')' (SyntaxError)
...out.<<(( content_tag(:div) do ).to_s); _erbout.<< "Example 2".f...
...                              ^
(erb):7: syntax error, unexpected keyword_end, expecting ')'
...erbout.<< "Example 2".freeze;  end ; _erbout.<< "`);\n".freeze
...                            ^~~
(erb):8: syntax error, unexpected end-of-input, expecting ')'
; _erbout
         ^
    from /home/anonymous/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/erb.rb:876:in `result'
    from /home/anonymous/anonymous/node_modules/rails-erb-loader/erb_transformer.rb:19:in `<top (required)>'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:38:in `perform'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
    from /home/anonymous/anonymous/bin/rails:9:in `<top (required)>'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
    from /home/anonymous/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
    from /home/anonymous/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/anonymous/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'

```

Please note that I already created a [question on StackOverflow](https://stackoverflow.com/questions/57926941/why-do-some-rails-helpers-fail-in-webpacker-erb-file) to this topic.

**Comment by rhys-vdw** [comment]
> When I included the automatically generated JavaScript pack file hello_erb.js.erb, the expected result was shown.

This file contains an error which has been reported before. It's not part of this project, nor is it generated by this project.
