### ISSUE TITLE
rails-erb-loader encountered an unexpected error while writing to stdin: "write EPIPE"

### ISSUE THREAD

**Issue by erickAvSanti** [usabilityhub/rails-erb-loader#91]
```
root@zavaleta:/home/webstore# rake assets:precompile RAILS_ENV=production
yarn install v1.22.5
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.84s.
Compiling...
Compilation failed:
Hash: 42fc777af3b4d1c6ac34
Version: webpack 4.44.1
Time: 4242ms
Built at: 09/01/2020 11:51:40 PM
 8 assets
Entrypoint application = js/application-8e25b9a32a7552174f1a.js js/application-8e25b9a32a7552174f1a.js.map
Entrypoint hello_erb = js/hello_erb-e923100a4cc16edb3f59.js js/hello_erb-e923100a4cc16edb3f59.js.map
Entrypoint website = js/website-512de1f9ba0649fe35f2.js js/website-512de1f9ba0649fe35f2.js.map
 [1] (webpack)/buildin/module.js 552 bytes {0} {2} [built]
 [3] ./app/javascript/packs/website.js 9.2 KiB {0} {2} [built]
 [4] (webpack)/buildin/global.js 905 bytes {0} [built]
 [6] ./app/javascript/packs/application.js 963 bytes {0} [built]
[10] ./app/javascript/channels/index.js 205 bytes {0} [built]
[11] ./app/javascript/channels sync _channel\.js$ 160 bytes {0} [built]
[14] ./app/javascript/packs/hello_erb.js.erb 325 bytes {1} [built] [failed] [1 error]
    + 8 hidden modules

ERROR in ./app/javascript/packs/hello_erb.js.erb
Module build failed (from ./node_modules/rails-erb-loader/index.js):
Error: spawn bin/rails EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)


rails-erb-loader encountered an unexpected error while writing to stdin: "write EPIPE". Please report this to the maintainers.
```

**Comment by PikachuEXE** [comment]
Please include more info
gem versions, ruby versions, related library versions...
Content for `./app/javascript/packs/hello_erb.js.erb`

Also please use code fence for log output next time to make it more readable

**Comment by erickAvSanti** [comment]
after any time, I solved that with gem 'mini_racer'
