### ISSUE TITLE
Error: rails-erb-loader failed with code: 1

### ISSUE THREAD

**Issue by yosupgurl** [usabilityhub/rails-erb-loader#92]
I get this error message when attempting to compile a .js.erb file with webpacker.

`ERROR in ./app/javascript/packs/freelancer.js.erb
Module build failed (from ./node_modules/rails-erb-loader/index.js):
Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (/mnt/c/Code/helloworld/node_modules/rails-erb-loader/index.js:128:16)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(erb):12:in `<main>': undefined method `render' for main:Object (NoMethodError)
        from /home/ben/.rbenv/versions/2.6.5/lib/ruby/2.6.0/erb.rb:901:in `eval'
        from /home/ben/.rbenv/versions/2.6.5/lib/ruby/2.6.0/erb.rb:901:in `result'
        from /mnt/c/Code/helloworld/node_modules/rails-erb-loader/erb_transformer.rb:20:in `<main>'`

My erb.js file looks like this. 

`module.exports = {
  test: /\.erb$/,
  enforce: 'pre',
  exclude: /node_modules/,
  use: [{
    loader: 'rails-erb-loader',
    options: {
      runner: (/^win/.test(process.platform) ? 'ruby ' : '') + 'bin/rails runner',
      env:        {
        ...process.env,
        DISABLE_SPRING: 1,
      },
    },
  }],
}
`
I've tried a few solutions here, involving changing the path to 'ruby bin\\ rails runner' since I'm on a windows machine, if I do that I get this error 'Error: spawn DISABLE_SPRING=1 ENOENT erb-rails-loader'.

I've tried adding 'options: { runner: 'DISABLE_SPRING=1 bin/rails runner' }' same ENOENT error.

I've tried adding the below snippet to erb.js, same exit code: 1

` engine: {
        name: 'erubis',
        includes: [
          'ActionView::Helpers',
          'Rails.application.routes.url_helpers'
        ]
      }`

I've also tried adding the helper in my transformer_erb file like such
` require 'erb'
    include Rails.application.routes.url_helpers
    ERB`

To no avail, not sure where to go from here. For context, i'm on WSL 2 running ubuntu 16.

**Comment by yosupgurl** [comment]
Sorry for pre-emptively opening this, moving my material to the existing case
